# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capones_recipes"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Simecek", "Simon H\u{fc}rlimann"]
  s.date = "2011-09-29"
  s.description = "A collection of useful capistrano recipes used by CyT GmbH and others."
  s.email = "roman.simecek@cyt.ch"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Capfile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "capones_recipes.gemspec",
    "config/deploy.rb",
    "config/deploy/production.rb",
    "config/deploy/staging.rb",
    "lib/capones_recipes.rb",
    "lib/capones_recipes/cookbook/rails.rb",
    "lib/capones_recipes/cookbook/rails31.rb",
    "lib/capones_recipes/cookbook/wikisigns.rb",
    "lib/capones_recipes/tasks/airbrake.rb",
    "lib/capones_recipes/tasks/airbrake/setup.rb",
    "lib/capones_recipes/tasks/airbrake/symlink.rb",
    "lib/capones_recipes/tasks/airbrake/templates/airbrake.rb",
    "lib/capones_recipes/tasks/bookyt.rb",
    "lib/capones_recipes/tasks/bookyt/setup.rb",
    "lib/capones_recipes/tasks/bookyt/templates/bookyt.rb",
    "lib/capones_recipes/tasks/database.rb",
    "lib/capones_recipes/tasks/database/mysql.rb",
    "lib/capones_recipes/tasks/database/sqlite.rb",
    "lib/capones_recipes/tasks/database/sync.rb",
    "lib/capones_recipes/tasks/katalog.rb",
    "lib/capones_recipes/tasks/katalog/import.rb",
    "lib/capones_recipes/tasks/katalog/katalog.rb",
    "lib/capones_recipes/tasks/kuhsaft.rb",
    "lib/capones_recipes/tasks/kuhsaft/setup.rb",
    "lib/capones_recipes/tasks/new_relic.rb",
    "lib/capones_recipes/tasks/new_relic/new_relic.rb",
    "lib/capones_recipes/tasks/rails.rb",
    "lib/capones_recipes/tasks/rails/bundler.rb",
    "lib/capones_recipes/tasks/rails/database_yml.rb",
    "lib/capones_recipes/tasks/rails/mod_rails.rb",
    "lib/capones_recipes/tasks/rails31.rb",
    "lib/capones_recipes/tasks/rails31/rails31.rb",
    "lib/capones_recipes/tasks/restful_authentication.rb",
    "lib/capones_recipes/tasks/restful_authentication/setup.rb",
    "lib/capones_recipes/tasks/settings_logic.rb",
    "lib/capones_recipes/tasks/settings_logic/settings_logic.rb",
    "lib/capones_recipes/tasks/thinking_sphinx.rb",
    "lib/capones_recipes/tasks/thinking_sphinx/thinking_sphinx.rb",
    "lib/capones_recipes/tasks/utilities.rb"
  ]
  s.homepage = "http://github.com/raskhadafi/capones-recipes"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Some capistrano recipes for use."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano_colors>, [">= 0"])
      s.add_runtime_dependency(%q<cap-recipes>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-ext>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<capistrano_colors>, [">= 0"])
      s.add_dependency(%q<cap-recipes>, [">= 0"])
      s.add_dependency(%q<capistrano-ext>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<capistrano_colors>, [">= 0"])
    s.add_dependency(%q<cap-recipes>, [">= 0"])
    s.add_dependency(%q<capistrano-ext>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

